//! Handles the unprocessed chart file.

use std::{error::Error, fmt::Display, io::{Read, Seek}};
use zip::{result::{ZipError, ZipResult}, *};

use thiserror::Error;
use displaydoc::Display;

use chart_metadata::*;

/// A wrapper around [`ZipArchive`], with some methods to get basic chart data.
pub struct RawChartFile<R: Read + Seek> {
    #[allow(missing_docs)]
    pub archive: ZipArchive<R>,
}

impl<R: Read + Seek> RawChartFile<R> {
    /// Creates a new [`RawChartFile`].
    pub fn new(reader: R) -> ZipResult<RawChartFile<R>> {
        ZipArchive::new(reader).map(|archive| RawChartFile { archive })
    }

    /// Gets the metadata from the chart file, if any.
    pub fn get_metadata(&mut self) -> Result<ChartInfo, MetadataError> {
        let mut de_errors = Vec::new();
        let info_yml_raw = match self.archive.by_name("info.yml") {
            Ok(file) => Some(file),
            Err(ZipError::FileNotFound) => None,
            err => Some(err?),
        };

        let info_yml = info_yml_raw.map(serde_yml::from_reader);
        if let Some(result) = info_yml {
            match result {
                Ok(info) => return Ok(info),
                Err(err) => de_errors.push(InfoDeserializationError::InfoYML(err)),
            }
        }

        if de_errors.len() > 0 {
            Err(InfoDeserializationErrorSet{ inner: de_errors }.into())
        } else {
            Err(MetadataError::NotFound)
        }
    }
}

/// Represents an error cause by any of the metadata formats.
#[derive(Debug, Display, Error)]
pub enum InfoDeserializationError {
    /// info.yml deserialization error: {0}
    InfoYML(#[from] serde_yml::Error),
}

/// A struct holding (possibly) multiple [`InfoDeserializationError`]s.
#[derive(Debug)]
pub struct InfoDeserializationErrorSet {
    #[allow(missing_docs)]
    pub inner: Vec<InfoDeserializationError>,
}

impl Display for InfoDeserializationErrorSet {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.inner.len() == 1 {
            self.inner[0].fmt(f)
        } else {
            let mut iter = self.inner.iter().enumerate();
            let len = iter.len();
            for _ in 0..(len - 1) {
                let (i, e) = iter.next().unwrap();
                f.write_fmt(format_args!("{}: ", i + 1))?;
                e.fmt(f)?;
                f.write_str("; ")?;
            }

            Ok(())
        }
    }
}

impl Error for InfoDeserializationErrorSet {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        Some(&self.inner[0])
    }
}

/// Any possible error when trying to read metadata from a raw chart file.
#[derive(Debug, Display, Error)]
pub enum MetadataError {
    /// zip file error: {0}
    ZipError(#[from] ZipError),
    /// deserialization error: {0}
    DeserializationError(#[from] InfoDeserializationErrorSet),
    /// metadata file not found, may be caused by missing or unsupported metadata file
    NotFound,
}

pub mod chart_metadata {
    #![allow(missing_docs)]

    use serde::*;
    use chrono::{DateTime, Utc};

    /// Possible chart formats generated by Phira zip.
    #[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
    #[repr(u8)]
    #[serde(rename_all = "lowercase")]
    pub enum ChartFormat {
        Rpe = 0,
        Pec,
        Pgr,
        Pbc,
    }

    /// Phira-compatible chart metadata.
    /// 
    /// The [Default] implementation is slightly modified.
    /// 
    /// Adapted from [Phira repo](https://github.com/TeamFlos/phira/blob/main/prpr/src/info.rs#L19).
    #[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
    #[serde(default)]
    #[serde(rename_all = "camelCase")]
    pub struct ChartInfo {
        pub id: Option<i32>,
        pub uploader: Option<i32>,

        pub name: String,
        pub difficulty: f32,
        pub level: String,
        pub charter: String,
        pub composer: String,
        pub illustrator: String,

        pub chart: String,
        pub format: Option<ChartFormat>,
        pub music: String,
        pub illustration: String,
        pub unlock_video: Option<String>,

        pub preview_start: f32,
        pub preview_end: Option<f32>,
        pub aspect_ratio: f32,
        pub background_dim: f32,
        pub line_length: f32,
        pub offset: f32,
        pub tip: Option<String>,
        pub tags: Vec<String>,

        pub intro: String,

        pub hold_partial_cover: bool,
        pub created: Option<DateTime<Utc>>,
        pub updated: Option<DateTime<Utc>>,
        pub chart_updated: Option<DateTime<Utc>>,
    }

    impl Default for ChartInfo {
        fn default() -> Self {
            Self {
                id: None,
                uploader: None,
    
                name: "New Chart".to_string(),
                difficulty: 14.,
                level: "IN Lv.14".to_string(),
                charter: "Charter".to_string(),
                composer: "Artist".to_string(),
                illustrator: "Illustrator".to_string(),
    
                chart: "chart.json".to_string(),
                format: None,
                music: "song.mp3".to_string(),
                illustration: "background.png".to_string(),
                unlock_video: None,
    
                preview_start: 0.,
                preview_end: None,
                aspect_ratio: 16. / 9.,
                background_dim: 0.6,
                line_length: 6.,
                offset: 0.,
                tip: None,
                tags: Vec::new(),
    
                intro: String::new(),
    
                hold_partial_cover: false,
    
                created: None,
                updated: None,
                chart_updated: None,
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::fs::File;
    use super::*;

    #[test]
    fn read_metadata() -> Result<(), Box<dyn std::error::Error>> {
        let file = File::open("../../test_assets/test_chart_1.zip")?;

        let mut raw_chart_file = RawChartFile::new(file)?;
        let metadata = raw_chart_file.get_metadata()?;
        println!("{:?}", metadata);

        Ok(())
    }
}
